# ---
# - name: Destroy
#   hosts: localhost
#   connection: local
#   gather_facts: false
#   # no_log: "{{ molecule_no_log }}"
#   tasks:
#     # Developer must implement.

#     # Mandatory configuration for Molecule to function.

#     - name: Populate instance config
#       ansible.builtin.set_fact:
#         instance_conf: {}

#     - name: Dump instance config
#       ansible.builtin.copy:
#         content: |
#           # Molecule managed

#           {{ instance_conf | to_json | from_json | to_yaml }}
#         dest: "{{ molecule_instance_config }}"
#         mode: "0600"
#       when: server.changed | default(false) | bool  # noqa no-handler


- name: Destroy molecule containers
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Stop and remove container
      delegate_to: localhost
      community.docker.docker_container:
        name: "{{ inventory_hostname }}"
        state: absent
        auto_remove: true

- name: Remove dynamic molecule inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove dynamic inventory file
      ansible.builtin.file:
        path: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        state: absent