dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: molecule
    image: geerlingguy/docker-debian10-ansible

# ---
# dependency:
#   name: galaxy
# driver:
#   name: docker
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
# platforms:
#   - name: instance
#     image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux8}-ansible:latest"
#     command: ""
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:rw
#     cgroupns_mode: host
#     privileged: true
#     pre_build_image: true
# provisioner:
#   name: ansible
# verifier:
#   name: ansible