---
name : CI
'on':
  pull_request:
  push:
    branch:
      - main

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8
          - debian10

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Setup python3
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'

      - name: Install test dependancies
        run: pip3 install docker yamllint ansible-lint molecule

      - name: Run molecule test
        run: molecule test

